
# coding: utf-8


"""add mitre fields

Revision ID: f1a1d0508d2f
Revises: b91bade09607
Create Date: 2026-03-30 13:56:49.756804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a1d0508d2f'
down_revision = 'b91bade09607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_rules_id'), 'detection_rules', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_source_ip'), 'incidents', ['source_ip'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('threat_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('source_port', sa.String(), nullable=True),
    sa.Column('destination_port', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('mitre_tactic', sa.String(), nullable=True),
    sa.Column('mitre_technique', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_destination_ip', 'threat_logs', ['destination_ip'], unique=False)
    op.create_index('idx_protocol', 'threat_logs', ['protocol'], unique=False)
    op.create_index('idx_severity', 'threat_logs', ['severity'], unique=False)
    op.create_index('idx_source_ip', 'threat_logs', ['source_ip'], unique=False)
    op.create_index(op.f('ix_threat_logs_created_at'), 'threat_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_threat_logs_destination_ip'), 'threat_logs', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_threat_logs_id'), 'threat_logs', ['id'], unique=False)
    op.create_index(op.f('ix_threat_logs_ingested_at'), 'threat_logs', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_threat_logs_risk_score'), 'threat_logs', ['risk_score'], unique=False)
    op.create_index(op.f('ix_threat_logs_severity'), 'threat_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_threat_logs_source_ip'), 'threat_logs', ['source_ip'], unique=False)
    op.create_index(op.f('ix_threat_logs_user_email'), 'threat_logs', ['user_email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_incident_source_ip'), table_name='incident')
    op.drop_table('incident')
    op.add_column('alerts', sa.Column('reputation', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('mitre_tactic', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('mitre_technique', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('incident_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_foreign_key(
        "fk_alerts_incident_id",
        "alerts",
        "incidents",
        ["incident_id"],
        ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_alerts_incident_id', 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_column('alerts', 'incident_id')
    op.drop_column('alerts', 'mitre_technique')
    op.drop_column('alerts', 'mitre_tactic')
    op.drop_column('alerts', 'reputation')
    op.create_table('incident',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('source_ip', sa.VARCHAR(), nullable=True),
    sa.Column('severity', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('owner', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_source_ip'), 'incident', ['source_ip'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_threat_logs_user_email'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_source_ip'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_severity'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_risk_score'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_ingested_at'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_id'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_destination_ip'), table_name='threat_logs')
    op.drop_index(op.f('ix_threat_logs_created_at'), table_name='threat_logs')
    op.drop_index('idx_source_ip', table_name='threat_logs')
    op.drop_index('idx_severity', table_name='threat_logs')
    op.drop_index('idx_protocol', table_name='threat_logs')
    op.drop_index('idx_destination_ip', table_name='threat_logs')
    op.drop_table('threat_logs')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_source_ip'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_detection_rules_id'), table_name='detection_rules')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
